-
  api_url : 'http://www.7timer.info/bin/astro.php?lon=113.2&lat=23.1&ac=0&unit=metric&output=json&tzshift=0'
  ui_url : "http://www.baidu.com"

  database:
        user : root
        password : 123